"""Request and response schemas for the Book resource."""

from datetime import date

from pydantic import BaseModel, ConfigDict, Field

# The earliest publication year the API accepts, roughly when the printing press
# reached Europe. Anything older is almost certainly a typo.
EARLIEST_PUBLISHED_YEAR = 1450

# "The current year" is read once when the application starts. The value becomes
# part of the published OpenAPI contract, so Swagger UI can show clients the
# accepted range instead of making them discover it through a failed request.
CURRENT_YEAR = date.today().year


class BookBase(BaseModel):
    """Define fields shared by every Book schema."""

    # Pydantic validates these constraints at runtime, and FastAPI copies them
    # into the OpenAPI document that Swagger UI and ReDoc display.
    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    title: str = Field(
        min_length=1,
        max_length=200,
        description="The title printed on the book.",
        examples=["The Pragmatic Programmer"],
    )
    author: str = Field(
        min_length=1,
        max_length=120,
        description="The name of the book's author.",
        examples=["Andrew Hunt"],
    )
    isbn: str = Field(
        min_length=1,
        max_length=20,
        description=(
            "The book's ISBN. Must be unique across books. ISBN-10 and ISBN-13 "
            "are both accepted, with or without hyphens."
        ),
        examples=["978-0-201-61622-4"],
    )
    published_year: int = Field(
        ge=EARLIEST_PUBLISHED_YEAR,
        le=CURRENT_YEAR,
        description=(
            f"The year the book was published, between "
            f"{EARLIEST_PUBLISHED_YEAR} and the current year."
        ),
        examples=[1999],
    )
    member_id: int = Field(
        gt=0,
        description="The identifier of the member who borrowed this book.",
        examples=[1],
    )


class BookCreate(BookBase):
    """Validate the body used to create a Book."""


class BookUpdate(BookBase):
    """Validate the replacement body used to update a Book."""


class BookResponse(BookBase):
    """Describe a Book returned by the API."""

    # The server generates the ID, so it appears in responses but never in
    # BookCreate or BookUpdate request bodies.
    id: int = Field(
        gt=0,
        description="The unique identifier generated by the server.",
        examples=[1],
    )
