"""Request and response schemas for the Member resource."""

from pydantic import BaseModel, ConfigDict, EmailStr, Field

# A Member's phone number must be a ten-digit North American number. The pattern
# accepts the separators people normally type and an optional country code, so
# "555-010-1234", "(555) 010 1234", and "+1 555.010.1234" are all valid. Keeping
# the rule in a named constant lets both the schema and the README describe the
# same source of truth.
US_PHONE_PATTERN = r"^(\+1[-. ]?)?\(?\d{3}\)?[-. ]?\d{3}[-. ]?\d{4}$"


class MemberBase(BaseModel):
    """Define fields shared by every Member schema."""

    # Pydantic validates these constraints at runtime, and FastAPI copies them
    # into the OpenAPI document that Swagger UI and ReDoc display.
    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    name: str = Field(
        min_length=1,
        max_length=120,
        description="The member's full name.",
        examples=["Ada Lovelace"],
    )
    email: EmailStr = Field(
        description="The member's email address. Must be unique across members.",
        examples=["ada.lovelace@example.com"],
    )
    membership_id: str = Field(
        min_length=1,
        max_length=32,
        description=(
            "The library card number printed on the member's card. "
            "Must be unique across members."
        ),
        examples=["LIB-000001"],
    )
    phone: str = Field(
        pattern=US_PHONE_PATTERN,
        description=(
            "A ten-digit phone number. Separators and an optional +1 country "
            "code are allowed."
        ),
        examples=["555-010-1234"],
    )


class MemberCreate(MemberBase):
    """Validate the body used to create a Member."""


class MemberUpdate(MemberBase):
    """Validate the replacement body used to update a Member."""


class MemberResponse(MemberBase):
    """Describe a Member returned by the API."""

    # The server generates the ID, so it appears in responses but never in
    # MemberCreate or MemberUpdate request bodies.
    id: int = Field(
        gt=0,
        description="The unique identifier generated by the server.",
        examples=[1],
    )
